Tip4Trip_aka/Models/Contact.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Tip4Trip_aka.Models
{
    public class Contact
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "You need to fill in a name")]
        [DisplayName("Name*")]
        public string Name { get; set; }
        [Required(ErrorMessage = "You need to fill in an email address")]
        [DataType(DataType.EmailAddress, ErrorMessage = "Your email address contains some errors")]
        [DisplayName("Email*")]
        public string Email { get; set; }
        [Required(ErrorMessage = "You need to fill in a subject")]
        [DisplayName("Subject*")]
        public string Subject { get; set; }
        [Required(ErrorMessage = "You need to fill in a message")]
        [DisplayName("Message*")]
        public string Message { get; set; }
    }
}

Tip4Trip_aka/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using Tip4Trip_aka.Models;
using Tip4Trip_aka.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;


namespace Tip4Trip_aka.Controllers
{
    
    public class HomeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
       
        public ActionResult Index()
        {
           

            return View();
        }
        public ActionResult MyTrip()
        {
            ApplicationUser user = System.Web.HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>().FindById(System.Web.HttpContext.Current.User.Identity.GetUserId());
            var MyHouses = db.Houses.Include(loc => loc.Location).Where(v => v.Owner.Id == user.Id);
            var Images = db.HouseImages.ToList();
            //List<string> paths = new List<string>();
            //foreach(House item in MyHouses) {paths.Add(Images.) }
            //var Reservations = db.Reservations.Where(b=>b.)
            UserHousesViewModel Myall = new UserHousesViewModel() { User = user, Houses = MyHouses.ToList(), HouseImages=Images };

                       
            return View(Myall);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();

        }
        [Authorize]
        public ActionResult MyReservations()
        {
            ApplicationUser user = System.Web.HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>().FindById(System.Web.HttpContext.Current.User.Identity.GetUserId());

            List<Reservation> reserlist = db.Reservations.Include(mmn => mmn.HouseRes.Location).Where(z => z.RenterId == user.Id).ToList();
            HouseReservationViewModel housereser = new HouseReservationViewModel();
            housereser.Reservations1 = reserlist;

            return View(housereser);

        }
        public ActionResult T4T()
        {
            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        public ActionResult Search(string searching, DateTime? Sstartdate, DateTime? Enddate , int? occupantsearch)
        {
            var Hous = db.Houses.Include(xxx => xxx.Reservations).Include(mmn => mmn.Location).Where(x => x.Location.NameCity.Contains(searching)).Where(l=>l.MaxOccupancy >= occupantsearch);
            if (occupantsearch == null)
            {  Hous = db.Houses.Include(xxx => xxx.Reservations).Include(mmn => mmn.Location).Where(x => x.Location.NameCity.Contains(searching)); }
                var res = db.Reservations.Where(c => (c.StartDate <= Sstartdate.Value) && (c.EndDate >= Sstartdate.Value)).ToList();
            var res2 = db.Reservations.Where(c => (c.StartDate >= Sstartdate.Value) && (c.StartDate <= Enddate.Value)).ToList();
            var res3 = db.Reservations.Where(c => (c.EndDate >= Enddate.Value) && (c.StartDate <= Enddate.Value)).ToList();
            var res12 = res.Concat(res2);
            var res4 = res3.Concat(res12);
            //var res4 = db.Reservations.Where(c => c.StartDate >= Sstartdate.Value && c.EndDate <= Enddate.Value).ToList();
            // var res2 = db.Reservations.Where(f => (f.EndDate >= Enddate.Value)&& (f.StartDate<= Enddate.Value));
            // var res3 = res.Concat(res2);
            if (Sstartdate == null && Enddate == null) { res4 = db.Reservations.ToList(); }

            var ImagesofHouses = db.HouseImages;

            HousesDates to_search_mas = new HousesDates { houses = Hous.ToList(), reservations = res4.Distinct().ToList() , HouseImages=ImagesofHouses.ToList() };
            if (to_search_mas == null) { return View(); }
            return View(to_search_mas);

            // var Hous = db.Houses.Include(xxx => xxx.Reservations).Include(mmn => mmn.Location).Where(x => x.Location.NameCity.Contains(searching) && x.Address.Contains(Address));

            // var res = db.Reservations.Where(c => (c.StartDate <= Sstartdate.Value) && (c.EndDate >= Sstartdate.Value));
            // var res2 = db.Reservations.Where(f => (f.EndDate >= Enddate.Value)&& (f.StartDate<= Enddate.Value));
            // var res4 = db.Reservations.Where(d=>(d.StartDate >= Sstartdate.Value) && (d.StartDate <= Enddate.Value));
            //var res3 = res.Concat(res2).Concat(res4);
            // if (Sstartdate == null && Enddate == null) { res3 = db.Reservations; }


            //  HousesDates to_search_mas = new HousesDates { houses = Hous.ToList(), reservations = res3.ToList() };
            // if (to_search_mas == null) { ViewBag.Message = "T4TripSearCh."; return View(); }

            // ViewBag.Message = "T4TripSearCh.";
            //  return View(to_search_mas);


        }
    }
}

Tip4Trip_aka/Controllers/HousesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Tip4Trip_aka.Models;
using Tip4Trip_aka.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System.IO;
using Microsoft.AspNet.Identity.EntityFramework;

namespace Tip4Trip_aka.Controllers
{
    [Authorize]
    public class HousesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private ApplicationUser du = new ApplicationUser();

        // GET: Houses
        //[Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            var houses = db.Houses.Include(h => h.Location).Include(xxx => xxx.Reservations);
            return View(houses.ToList());
        }
        [HttpGet]
        public ActionResult Imageget(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            House house = db.Houses.Find(id);
            if (house == null)
            {
                return HttpNotFound();
            }
            HouseImage hsimg = new HouseImage() { housId = house.Id };
            return View(hsimg);
        }
        [HttpPost]
        public ActionResult Imageget(HouseImage membervalues)
        {
            //Use Namespace called :  System.IO  
            string FileName = Path.GetFileNameWithoutExtension(membervalues.ImageFile.FileName);

            //To Get File Extension  
            string FileExtension = Path.GetExtension(membervalues.ImageFile.FileName);

            //Add Current Date To Attached File Name  
            FileName =  FileName.Trim() + FileExtension;

            //Get Upload path from Web.Config file AppSettings.  
            string UploadPath = @"C:\T4T1105eva\Tip4Trip_aka\UserImages\";

            //Its Create complete path to store in server.  
            membervalues.ImagePath = UploadPath + FileName;

            //To copy and save file into server.  
            membervalues.ImageFile.SaveAs(membervalues.ImagePath);
          
              HouseImage _member = new HouseImage();
              _member.ImagePath = membervalues.ImagePath;
            _member.housId = membervalues.housId;
            //   _member.Name = membervalues.Name;
            //    _member.PhoneNumber = membervalues.PhoneNumber;
            //  db.tblMembers.Add(_member);
            //    db.SaveChanges();
            if (ModelState.IsValid)
            {
                db.HouseImages.Add(_member);
                db.SaveChanges();
                return RedirectToAction("MyTrip","Home");
            }
            return View();
        }

        public ActionResult mazi(int idilicious)
        {
            
            List<House> housesList3 = db.Houses.ToList();
            // var housesViewModelList = housesList.Select(x => new HouseReservationViewModel { House = x, Reservations1 = x.Reservations }).ToList();
            var housesList = db.Houses.Include(c => c.Location).Include(y => y.Reservations).Where(xs => xs.Id.Equals(idilicious)).ToList();
            var ReservationsList = db.Reservations.Where(xc=>xc.HouseId.Equals(idilicious)).ToList();
            ApplicationUser user = System.Web.HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>().FindById(System.Web.HttpContext.Current.User.Identity.GetUserId());
            if (idilicious >= db.Houses.Min(n=>n.Id) && idilicious <= db.Houses.Max(x=>x.Id))
            {
                HouseReservationViewModel ViewModel = new HouseReservationViewModel
                {
                    House = housesList.First(),
                    Reservations1 = ReservationsList,
                    Name=user.FullName
                    
                    

                };

                return View(ViewModel);
            }
            else
            { return Content("Wrong Id , Try again"); }
        }

        // GET: Houses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            House house = db.Houses.Find(id);
            if (house == null)
            {
                return HttpNotFound();
            }

            ApplicationUser user = System.Web.HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>().FindById(System.Web.HttpContext.Current.User.Identity.GetUserId());
            List<House> list = new List<House> { };
            var Images = db.HouseImages.ToList();
           
            list.Add(house);
            UserHousesViewModel ViewModel = new UserHousesViewModel { User = user, Houses = list , HouseImages = Images};

            return View(ViewModel);
        }

        // GET: Houses/Create
        public ActionResult Create()
        {
            
            ApplicationUser user = System.Web.HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>().FindById(System.Web.HttpContext.Current.User.Identity.GetUserId());
            House ase = new House() ;
            List<House> list = new List<House> {  };
            list.Add(ase)
;            UserHousesViewModel ViewModel = new UserHousesViewModel { User = user, Houses = list };
            ViewBag.LocationId = new SelectList(db.Locations, "Id", "NameCity");
            return View(ViewModel);
        }

        // POST: Houses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,OwnerId,Address,Description,LocationId,MaxOccupancy,PriceperNight")] House house)
        {
            ApplicationUser user = System.Web.HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>().FindById(System.Web.HttpContext.Current.User.Identity.GetUserId());
            var UserManagers = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
            var AuthManager = HttpContext.GetOwinContext().Authentication;
            if (User.IsInRole("Renter"))
            {

                UserManagers.RemoveFromRole(user.Id, "Renter");

                UserManagers.AddToRole(user.Id, "Owner");

                AuthManager.SignOut(DefaultAuthenticationTypes.ApplicationCookie, DefaultAuthenticationTypes.ExternalCookie);
            }
            // house.Owner = user;
            // house.OwnerId = user.Id;
            if (ModelState.IsValid)
            {
                db.Houses.Add(house);
                db.SaveChanges();
                return RedirectToAction("MyTrip","Home");
            }
            List<House> list = new List<House> { };
            list.Add(house);
            ViewBag.LocationId = new SelectList(db.Locations, "Id", "NameCity", house.LocationId);
            UserHousesViewModel ViewModel = new UserHousesViewModel { User = user, Houses = list };
            return View(ViewModel);
        }

        // GET: Houses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            House house = db.Houses.Find(id);
            if (house == null)
            {
                return HttpNotFound();
            }
            ViewBag.LocationId = new SelectList(db.Locations, "Id", "NameCity", house.LocationId);
            return View(house);
        }

        // POST: Houses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,Owner,Address,Description,LocationId,MaxOccupancy,PriceperNight")] House house)
        {
            if (ModelState.IsValid)
            {
                db.Entry(house).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.LocationId = new SelectList(db.Locations, "Id", "NameCity", house.LocationId);
            return View(house);
        }

        // GET: Houses/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            House house = db.Houses.Find(id);
            if (house == null)
            {
                return HttpNotFound();
            }
            return View(house);
        }

        // POST: Houses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)

        {

            ApplicationUser user = System.Web.HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>().FindById(System.Web.HttpContext.Current.User.Identity.GetUserId());

            var UserManagers = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));

            if (User.IsInRole("Owner"))

            {

                if (db.Houses.Where(g => g.OwnerId == user.Id).Count() == 1)
                {

                    UserManagers.RemoveFromRole(user.Id, "Owner");

                    UserManagers.AddToRole(user.Id, "Renter");

                }

            }
            House house = db.Houses.Find(id);

            db.Houses.Remove(house);

            db.SaveChanges();

            return RedirectToAction("Index");

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)

Tip4Trip_aka/Views/Home/About.cshtml
@{
    ViewBag.Title = "Who we are";
}

<header id="about-section">

    <div class="mt-4 mb-3 pt-5 pb-5">
        <div class="home-inner container">
            <div class="row">
                <div class="col-lg-8 image-about-back pr-4">
                    <h1 class="display-4">
                        We are
                        <strong>your best</strong> vacation
                        <strong>place</strong>
                    </h1>
                    <br />
                    <br />
                    <br />
                    Tip4Trip is a rent agency offering vacation renting solutions for
                    residence owners and renters. Tip4Trip uses the most sophisticated procedures, in
                    way to make sure that your online real-estate registration will affortable and easy to handle.
                    Tip4Trip makes Online reservation a simple and enjoyable experience!
                </div>

                <div class="col-lg-4 d-lg-block">
                    <h1 class="display-4">
                        Reasons to Choose us
                    </h1>
                    <br />
                    <br />
                    <div class="d-flex">
                        <div class="p-4 align-self-start" style="color:teal;">
                            <span class="fa-stack">
                                <i class="fa fa-circle-thin fa-stack-2x"></i>
                                <i class="fa fa-check fa-stack-1x"></i>

                            </span>
                        </div>
                        <div class="p-4 align-self-end">Effectiveness</div>
                    </div>

                    <div class="d-flex">
                        <div class="p-4 align-self-start" style="color:teal;">
                            <span class="fa-stack">
                                <i class="fa fa-circle-thin fa-stack-2x"></i>
                                <i class="fa fa-check fa-stack-1x"></i>

                            </span>
                        </div>
                        <div class="p-4 align-self-end">Speed</div>
                    </div>

                    <div class="d-flex">
                        <div class="p-4 align-self-start" style="color:teal;">
                            <span class="fa-stack">
                                <i class="fa fa-circle-thin fa-stack-2x"></i>
                                <i class="fa fa-check fa-stack-1x"></i>

                            </span>
                        </div>
                        <div class="p-4 align-self-end">Affortable Prices</div>
                    </div>
                </div>


            </div>
        </div>
    </div>

</header>

Tip4Trip_aka/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
@*<h3>@ViewBag.Message</h3>*@

@model Tip4Trip_aka.Models.Contact
<div class="container-fluid">
    <div class="text-left  mt-4 mb-3 pt-5 pb-5 pl-5">
        <h2>@ViewBag.Title Us</h2>
    </div>
    <div id="contact-form" class="row">


        <div class="col-md-4 p-5 ">
            <div class="card-body shadow ">
                <address>
                    35, Tsimiski Street<br />
                    Thessaloniki, 54621<br />
                    Greece<br />
                    <abbr title="Phone">Phone:</abbr>
                    +30 2310 331506<br />
                    <abbr title="Fax">Fax:</abbr>
                    +30 2310 331507
                </address>

                <address>
                    <strong>Email:</strong>   <a href="mailto:info@tip4trip.com">info@tip4trip.com</a><br />

                </address>
            </div>
        </div>
        <div class="col-md-8 p-5">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal" style="width:100%;">

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Message, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Message, new { htmlAttributes = new { @class = "form-control", rows = "3" } })
                            @Html.ValidationMessageFor(model => model.Message, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Send" class="btn btn-info" />
                        </div>
                    </div>
                </div>

            }
        </div>
    </div>
    <br />
    <br />
    <div class="kc-elm kc-css-363789 kc_google_maps kc_shortcode">
        <div style="height: 350px" class="kc-google-maps">
            <iframe src="https://maps.google.com/maps?width=100%&height=600&hl=en&q=Tsimiski%2035%2C%20Thessaloniki%2C%20Greece+(Tip4Trip)&ie=UTF8&t=&z=14&iwloc=B&output=embed" width=100% height="350" frameborder="0" style="border:0" allowfullscreen></iframe>
        </div>
    </div>
</div>

Tip4Trip_aka/Views/Home/MyReservations.cshtml
@model Tip4Trip_aka.ViewModels.HouseReservationViewModel
@{
                /**/

                ViewBag.Title = "MyReservations";
}

<h2>My Reservations</h2>

<style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

    td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #dddddd;
    }
</style>


    @*<h5><b>House Location:</b>&nbsp;@item.HouseRes.Address , @item.HouseRes.Location.NameCity </h5>


        <p>@item.StartDate</p>
        <p>@item.EndDate</p>*@

    
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Reservation Reference ID</th>
                    <th>House Location</th>
                    <th>House Address</th>
                    <th>Reservation Check In Date</th>
                    <th>Reservation Check Out Date</th>
                </tr>
            </thead>
            @foreach (Tip4Trip_aka.Models.Reservation item in Model.Reservations1)
            {
                <tbody>
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.HouseRes.Location.NameCity</td>
                        <td>@item.HouseRes.Address</td>
                        <td>@item.StartDate.ToShortDateString()</td>
                        <td>@item.EndDate.ToShortDateString()</td>
                    </tr>
                </tbody>
            }
            </table>
   


            @Html.ActionLink("Back to MyT4T", "T4T", "Home")

Tip4Trip_aka/Views/Home/MyTrip.cshtml
@model Tip4Trip_aka.ViewModels.UserHousesViewModel
@{
    ViewBag.Title = "MyTrip";
}

<h2>My Houses Quickview</h2>

@*<h4>Hello @Model.User.Email</h4>*@

@*@Html.ActionLink("Add new House", "Create", "Houses")*@
<span>
    <button class="btn btn-default my-2 my-sm-0 m-1" type="button">
        <i class="fa fa-drivers-license"></i><a href="@Url.Action("Create", "Houses")"> Add a new house</a>
    </button>
</span>
<table class="table table-bordered text-center">
    <thead>
        <tr>
            <th>House Reference ID</th>
            <th>House Title</th>
            <th>House Location</th>
            <th>House Address</th>
            <th>Max Occupancy</th>
            @*<th>Price per Night Charged</th>*@
            @*<th>House Images</th>*@
            <th>More Actions</th>
        </tr>
    </thead>
    @foreach (Tip4Trip_aka.Models.House it in Model.Houses)
    {
        <tbody>
            <tr>
                <td>@it.Id</td>
                <td>@it.Title</td>
                <td>@it.Location.NameCity</td>
                <td>@it.Address</td>
                <td>@it.MaxOccupancy</td>
                @*<td>@it.PriceperNight</td>
                <td>
                    @foreach (var obje in Model.HouseImages.Where(c => c.housId == it.Id))
                    {
                        if (obje.ImagePath != null)
                        {
                            string FileName = Path.GetFileNameWithoutExtension(obje.ImagePath);

                            //To Get File Extension
                            string FileExtension = Path.GetExtension(obje.ImagePath);

                            //Add Current Date To Attached File Name
                            FileName = FileName.Trim() + FileExtension;
                            <img src="../../UserImages/@FileName" class="img-thumbnail" alt="An image should be here!" width="100" height="50" />

                        }

                    }
                </td>*@
                @*<td>@Html.ActionLink("Detailas", "Details", "Houses", new { id = it.Id }) </td>
                    <td><a href="@Url.Action("Details", "Houses",new { id = it.Id })"></a></td>*@
                <td><a href="@Url.Action("Details", "Houses",new { id = it.Id })">Details</a></td>


            </tr>
        </tbody>


    }
</table>
@Html.ActionLink("Back to MyT4T", "T4T", "Home")

Tip4Trip_aka/Views/Home/t4t.cshtml
@*@{
        ViewBag.Title = "t4t";
    }

    <h2>t4t</h2>

    <form method="post" id="signin" action="@Url.Action("MyTrip", "Home")">

        <input type="button" value="MyTip4Trip" />
        <ol>
            <li>@Html.ActionLink("MyHouses", "MyTrip", "Home")</li>
        </ol>
    </form>*@

@{

    ViewBag.Title = "T4T";

}

<div class="pl-lg-5 pr-lg-5 pt-lg-4">
    @if (User.IsInRole("Owner") || User.IsInRole("Admin"))
    {

        <span>
            <button class="btn btn-default my-2 my-sm-0 m-1" type="button">
                <i class="fa fa-home"></i><a href="@Url.Action("MyTrip", "Home")"> My Houses</a>
            </button>
        </span>
    }
    @if (User.IsInRole("Renter"))
    {

        <span>
            <button class="btn btn-default my-2 my-sm-0 m-1" type="button">
                <i class="fa fa-drivers-license"></i><a href="@Url.Action("Create", "Houses")"> Become a host!</a>
            </button>
        </span>
    }
    <span style="color:white !important;">
        <button class="btn btn-default my-2 my-sm-0 m-1" type="button">
            <i class="fa fa-book"></i><a href="@Url.Action("MyReservations", "Home")"> My Reservations</a>
        </button>
    </span>
</div>